image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: bundle install
    command: bundle exec jekyll serve -H 0.0.0.0
github:
    prebuilds:
        pullRequestsFromForks: true
